# Generated by Django 5.1 on 2024-08-17 15:54

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('employee_id', models.CharField(default='Employee ID', max_length=100)),
                ('first_name', models.CharField(default='First Name', max_length=100)),
                ('last_name', models.CharField(default='Last Name', max_length=100)),
                ('email', models.CharField(default='Email', max_length=100)),
                ('basic_salary', models.CharField(default='Basic Salary', max_length=100)),
                ('conveyance_allowance', models.CharField(default='Conveyance Allowance', max_length=100)),
                ('medical_allowance', models.CharField(default='Medical Allowance', max_length=100)),
                ('other_allowances', models.CharField(default='Other Allowances', max_length=100)),
                ('provident_fund', models.CharField(default='Provident Fund', max_length=100)),
                ('professional_tax', models.CharField(default='Professional Tax', max_length=100)),
                ('income_tax', models.CharField(default='Income Tax', max_length=100)),
                ('other_deductions', models.CharField(default='Other Deductions', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(default=datetime.datetime.now)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conveyance_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('provident_fund', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salary_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10, null=True)),
                ('total_records', models.IntegerField(blank=True, null=True)),
                ('processed_records', models.IntegerField(blank=True, default=0, null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
